export const CART_REQUEST = 'CART_REQUEST';
export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_LIST_FAIL';

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_LIST_FAIL';

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL';
